# Generated by Django 4.1.2 on 2022-10-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upscale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='lrImage',
            new_name='image',
        ),
    ]
